### ISSUE TITLE
Wrong design on 'д'

### ISSUE THREAD

**Issue by emmamarichal** [hyvyys/Tektur#6]
Hi! I inspected the files and saw a 'g' drawn in the 'д' unicode.

Can you check this?
See the discussion here: https://github.com/google/fonts/issues/8138

<img width="1552" alt="Screenshot 2024-09-11 at 11 07 23" src="https://github.com/user-attachments/assets/115bf7a3-1a32-42ad-bbb1-99bb734abc42">

thank you!

**Comment by emmamarichal** [comment]
<img width="1165" alt="Screenshot 2024-09-11 at 11 08 34" src="https://github.com/user-attachments/assets/fb23bf54-751d-49d0-aa0e-a8786a59c59b">

**Comment by hyvyys** [comment]
Hi Emma, this is by design. This is a д form found in some display fonts, in handwriting and italic fonts, as well as in fonts for the Bulgarian market.

Some examples:

![Screenshot 2024-09-11 at 18 53 49](https://github.com/user-attachments/assets/680dd140-7565-4f1e-9ae7-f07979e2aaf7)
![Screenshot 2024-09-11 at 18 53 57](https://github.com/user-attachments/assets/af413772-40aa-437b-9c18-f3c6dd05c88c)
![Screenshot 2024-09-11 at 18 54 33](https://github.com/user-attachments/assets/fc179725-dcc5-4963-b0f1-0398f9bc0136)
![Screenshot 2024-09-11 at 18 54 40](https://github.com/user-attachments/assets/89a98dc1-3563-4fb3-8ca1-fb26ff5001b3)
![Screenshot 2024-09-11 at 18 54 44](https://github.com/user-attachments/assets/352453ac-3bd8-4c61-8722-2f08f735130b)
![Screenshot 2024-09-11 at 18 58 59](https://github.com/user-attachments/assets/ff0f3bc6-82c8-4040-bbce-a33adaf0201f)
![Screenshot 2024-09-11 at 18 59 07](https://github.com/user-attachments/assets/9dad689a-9609-4ca2-8501-e50be7de70d2)
![Screenshot 2024-09-11 at 18 59 13](https://github.com/user-attachments/assets/e352b8be-05b1-4240-9b07-a33cd86531e5)
![Screenshot 2024-09-11 at 18 59 20](https://github.com/user-attachments/assets/358dd035-ab31-4906-a741-5e20d8b76e9e)
![Screenshot 2024-09-11 at 18 59 45](https://github.com/user-attachments/assets/b2906d78-bb84-4723-95d0-9fb27252c600)
![Screenshot 2024-09-11 at 18 59 50](https://github.com/user-attachments/assets/7c13a68d-670c-4e15-85bc-182e6afa677f)


Fun fact: you can find this form in the Civil Type:

![99be1c80-3fc6-11e3-a7f3-14dae9b62a82](https://github.com/user-attachments/assets/8827f938-3d52-4402-8952-4b0ef7b82d1d)

**Comment by emmamarichal** [comment]
Oh ok my bad, I'm sorry! Then all is good :) thank you for the explanation!

**Comment by janpier91** [comment]
this is true, but this font is not cursive, it is more similar to block letters (digital block letters we could say in my opinion) and online sites almost never use the "g" from what I have seen, this is because they use block fonts or similar like this. However I am in contact with its programmer who should update it

**Comment by emmamarichal** [comment]
Ok, feel free to open this issue again when it's ready: https://github.com/google/fonts/issues/8138
